//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Message;
/**
 * Class generated from <tt>Message.msg:28</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Message
 * {
 *     int seqNum;
 *     string payload;
 *     char trailer;
 *     int frameType;
 *     int ackNum;
 *     int errorType;
 *     string errorString;
 *     int messageState;
 *     int messageType; // 0 -> coordinator message
 *    					// 1 -> node message
 * }
 * </pre>
 */
class Message : public ::omnetpp::cPacket
{
  protected:
    int seqNum = 0;
    omnetpp::opp_string payload;
    char trailer = 0;
    int frameType = 0;
    int ackNum = 0;
    int errorType = 0;
    omnetpp::opp_string errorString;
    int messageState = 0;
    int messageType = 0;

  private:
    void copy(const Message& other);

  protected:
    bool operator==(const Message&) = delete;

  public:
    Message(const char *name=nullptr, short kind=0);
    Message(const Message& other);
    virtual ~Message();
    Message& operator=(const Message& other);
    virtual Message *dup() const override {return new Message(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual char getTrailer() const;
    virtual void setTrailer(char trailer);

    virtual int getFrameType() const;
    virtual void setFrameType(int frameType);

    virtual int getAckNum() const;
    virtual void setAckNum(int ackNum);

    virtual int getErrorType() const;
    virtual void setErrorType(int errorType);

    virtual const char * getErrorString() const;
    virtual void setErrorString(const char * errorString);

    virtual int getMessageState() const;
    virtual void setMessageState(int messageState);

    virtual int getMessageType() const;
    virtual void setMessageType(int messageType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Message& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Message& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Message *fromAnyPtr(any_ptr ptr) { return check_and_cast<Message*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGE_M_H

